# Generated by Django 2.2.5 on 2020-03-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient_personal_info',
            name='patient_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
