# Generated by Django 2.2.5 on 2020-03-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200317_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dosage',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.TextField(default=''),
        ),
    ]
