# Generated by Django 2.2.5 on 2020-03-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20200317_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_personal_info',
            name='other_mentions',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='patient_personal_info',
            name='weekend_habits',
            field=models.TextField(default=''),
        ),
    ]
