# Generated by Django 2.2.5 on 2020-03-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20200317_0608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_personal_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='patient_personal_info',
            name='patient_id',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
